steps:    
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
    id: 'upload'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy optimizer --source Optimizer --function optimize --base-image python312 --region europe-west1 --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY