steps:    
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable'
    id: 'upload'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy optimizer --source . --function optimize --base-image python312

options:
  logging: CLOUD_LOGGING_ONLY