steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'restore'
    entrypoint: 'dotnet'
    args: ['restore']

  - name: 'bash'
    id: 'set-backend-address'
    entrypoint: 'sed'
    args:
    - '-i'
    - '-e'
    - 's|{BACKEND_ADDRESS}|${_BACKEND_ADDRESS}|'
    - '-e'
    - 's|<base href=".*"|<base href="${_BASE_PATH}"|'
    - 'Web/wwwroot/index.html'
  
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'publish'
    entrypoint: 'dotnet'
    args: ['publish', 'Web/Web.csproj', '-c', 'Release', '-o', '/workspace/out', '--no-restore']
    
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable'
    id: 'upload'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud storage rsync /workspace/out gs://einsatzplaner-wasm/ -r --delete-unmatched-destination-objects

options:
  logging: CLOUD_LOGGING_ONLY