steps:    
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
    id: 'upload'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy optimizer --source . --entry-point optimize --runtime python312 --trigger-http

options:
  logging: CLOUD_LOGGING_ONLY