steps:
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'restore'
    entrypoint: 'dotnet'
    args: ['restore']

  - name: 'bash'
    id: 'set-backend-address'
    entrypoint: 'sed'
    args:
    - '-i'
    - 's|{BACKEND_ADDRESS}|${_BACKEND_ADDRESS}|'
    - 'Web/wwwroot/appsettings.Production.json'
    - 's|{BASE_PATH}|${_BASE_PATH}|'
    - 'Web/wwwroot/appsettings.Production.json'
  
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'publish'
    entrypoint: 'dotnet'
    args: ['publish', 'Web/Web.csproj', '-c', 'Release', '-o', '/workspace/out', '--no-restore']
    
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable'
    id: 'upload'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud storage cp -r /workspace/out/* gs://einsatzplaner-wasm/

options:
  logging: CLOUD_LOGGING_ONLY