FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY Api/*.csproj Api/
COPY DTO/*.csproj DTO/
COPY Web/*.csproj Web/
RUN dotnet restore

COPY DTO/. DTO/
COPY Web/. Web/
RUN dotnet publish Web/Web.csproj -c Release -o /out --no-restore

FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable
COPY --from=build /out/wwwroot .
RUN gcloud storage cp . gs://einsatzplaner-wasm/