FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY Api/*.csproj Api/
COPY DTO/*.csproj DTO/
COPY Web/*.csproj Web/
RUN dotnet restore

COPY DTO/. DTO/
COPY Web/. Web/
RUN dotnet publish Web/Web.csproj -c Release -o /out --no-restore

FROM nginx:alpine AS runtime
WORKDIR /usr/share/nginx/html
COPY --from=build /out/wwwroot .
COPY Web/nginx.conf /etc/nginx/nginx.conf
COPY Web/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]